# Generated by Django 3.1.7 on 2021-05-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='type',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
