# Generated by Django 3.1.7 on 2021-05-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210529_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='image',
            field=models.ImageField(default='images/default2.jpg', upload_to='images/'),
        ),
    ]
